server:
  port: ${SERVER_PORT:8082}

spring:
  docker:
    compose:
      enabled: true
      file: ../../docker-compose.yml
      lifecycle-management: start-only
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bantads}?currentSchema=${POSTGRES_SCHEMA:schema_conta}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

cqrs:
  rabbitmq:
    exchange: conta.events
    queue: conta.sync.queue
    routing-key: conta.operacao.*

saga:
  rabbitmq:
    exchange: ${SAGA_RABBITMQ_EXCHANGE:bantads.saga}
    queue:
      conta:
        criar:
          command: ${SAGA_RABBITMQ_QUEUE_CONTA_CRIAR_COMMAND:conta.criar.command}
        alterar-limite:
          command: ${SAGA_RABBITMQ_QUEUE_CONTA_ALTERAR_LIMITE_COMMAND:conta.alterar-limite.command}
        consultar-gerente-mais-contas:
          command: ${SAGA_RABBITMQ_QUEUE_CONTA_CONSULTAR_GERENTE_MAIS_CONTAS_COMMAND:conta.consultar-gerente-mais-contas.command}
        atribuir-gerente:
          command: ${SAGA_RABBITMQ_QUEUE_CONTA_ATRIBUIR_GERENTE_COMMAND:conta.atribuir-gerente.command}
        selecionar-gerente-para-nova-conta:
          command: ${SAGA_RABBITMQ_QUEUE_CONTA_SELECIONAR_GERENTE_PARA_NOVA_CONTA_COMMAND:conta.selecionar-gerente-para-nova-conta.command}
        reatribuir-contas-gerente:
          command: ${SAGA_RABBITMQ_QUEUE_CONTA_REATRIBUIR_CONTAS_GERENTE_COMMAND:conta.reatribuir-contas-gerente.command}
    routing-key:
      conta:
        criar:
          command: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_CRIAR_COMMAND:conta.criar.command}
          sucesso: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_CRIAR_SUCESSO:conta.criada}
          falha: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_CRIAR_FALHA:conta.criacao.falhou}
        alterar-limite:
          command: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_ALTERAR_LIMITE_COMMAND:conta.alterar-limite.command}
          sucesso: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_ALTERAR_LIMITE_SUCESSO:conta.limite-alterado}
          falha: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_ALTERAR_LIMITE_FALHA:conta.alteracao-limite.falhou}
        consultar-gerente-mais-contas:
          command: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_CONSULTAR_GERENTE_MAIS_CONTAS_COMMAND:conta.consultar-gerente-mais-contas}
          sucesso: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_CONSULTAR_GERENTE_MAIS_CONTAS_SUCESSO:conta.gerente-mais-contas-consultado}
          falha: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_CONSULTAR_GERENTE_MAIS_CONTAS_FALHA:conta.consulta-gerente-mais-contas.falhou}
        atribuir-gerente:
          command: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_ATRIBUIR_GERENTE_COMMAND:conta.atribuir-gerente}
          sucesso: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_ATRIBUIR_GERENTE_SUCESSO:conta.gerente-atribuido}
          falha: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_ATRIBUIR_GERENTE_FALHA:conta.atribuicao-gerente.falhou}
        selecionar-gerente-para-nova-conta:
          command: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_SELECIONAR_GERENTE_PARA_NOVA_CONTA_COMMAND:conta.selecionar-gerente-para-nova-conta}
          sucesso: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_SELECIONAR_GERENTE_PARA_NOVA_CONTA_SUCESSO:conta.gerente-para-nova-conta-selecionado}
          falha: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_SELECIONAR_GERENTE_PARA_NOVA_CONTA_FALHA:conta.selecao-gerente-para-nova-conta.falhou}
        reatribuir-contas-gerente:
          command: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_REATRIBUIR_CONTAS_GERENTE_COMMAND:conta.reatribuir-contas-gerente}
          sucesso: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_REATRIBUIR_CONTAS_GERENTE_SUCESSO:conta.contas-reatribuidas}
          falha: ${SAGA_RABBITMQ_ROUTING_KEY_CONTA_REATRIBUIR_CONTAS_GERENTE_FALHA:conta.reatribuicao-contas.falhou}
