spring.application.name=cliente
server.port=${SERVER_PORT:8082}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bantads}?currentSchema=schema_cliente
spring.datasource.username=${POSTGRES_USER:postgres_user}
spring.datasource.password=${POSTGRES_PASSWORD:postgres_bantads}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=schema_cliente

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:bantads}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:bantads}

# Saga Messaging
saga.rabbitmq.exchange=${SAGA_RABBITMQ_EXCHANGE:bantads.saga}
saga.rabbitmq.queue.cliente.aprovar.command=${SAGA_RABBITMQ_QUEUE_CLIENTE_APROVAR_COMMAND:cliente.aprovar.command}
saga.rabbitmq.routing-key.cliente.aprovar.command=${SAGA_RABBITMQ_ROUTING_KEY_CLIENTE_APROVAR_COMMAND:cliente.aprovar}
saga.rabbitmq.routing-key.cliente.aprovar.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_CLIENTE_APROVAR_SUCESSO:cliente.aprovado}
saga.rabbitmq.routing-key.cliente.aprovar.falha=${SAGA_RABBITMQ_ROUTING_KEY_CLIENTE_APROVAR_FALHA:cliente.aprovacao.falhou}
saga.rabbitmq.queue.cliente.rejeitar.command=${SAGA_RABBITMQ_QUEUE_CLIENTE_REJEITAR_COMMAND:cliente.rejeitar.command}
saga.rabbitmq.routing-key.cliente.rejeitar.command=${SAGA_RABBITMQ_ROUTING_KEY_CLIENTE_REJEITAR_COMMAND:cliente.rejeitar}
saga.rabbitmq.routing-key.cliente.rejeitar.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_CLIENTE_REJEITAR_SUCESSO:cliente.rejeitado}
saga.rabbitmq.routing-key.cliente.rejeitar.falha=${SAGA_RABBITMQ_ROUTING_KEY_CLIENTE_REJEITAR_FALHA:cliente.rejeicao.falhou}
