spring.application.name=ms-gerente
server.port=${SERVER_PORT:8084}

# Docker Compose integration
spring.docker.compose.lifecycle-management=start-only
# spring.docker.compose.file=../docker-compose.yml

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bantads}?currentSchema=schema_gerente
spring.datasource.username=${POSTGRES_USER:postgres_user}
spring.datasource.password=${POSTGRES_PASSWORD:postgres_bantads}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=schema_gerente

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:bantads}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:bantads}

# Saga Messaging - shared exchange
saga.rabbitmq.exchange=${SAGA_RABBITMQ_EXCHANGE:bantads.saga}

# Saga Inserir Gerente
saga.rabbitmq.queue.gerente.inserir.command=${SAGA_RABBITMQ_QUEUE_GERENTE_INSERIR_COMMAND:gerente.inserir.command}
saga.rabbitmq.routing-key.gerente.inserir.command=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_INSERIR_COMMAND:gerente.inserir}
saga.rabbitmq.routing-key.gerente.inserir.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_INSERIR_SUCESSO:gerente.inserido}
saga.rabbitmq.routing-key.gerente.inserir.falha=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_INSERIR_FALHA:gerente.insercao.falhou}
saga.rabbitmq.queue.gerente.listar-ativos-detalhado.command=${SAGA_RABBITMQ_QUEUE_GERENTE_LISTAR_ATIVOS_DETALHADO_COMMAND:gerente.listar-ativos-detalhado.command}
saga.rabbitmq.routing-key.gerente.listar-ativos-detalhado.command=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_LISTAR_ATIVOS_DETALHADO_COMMAND:gerente.listar-ativos-detalhado}
saga.rabbitmq.routing-key.gerente.listar-ativos-detalhado.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_LISTAR_ATIVOS_DETALHADO_SUCESSO:gerente.ativos-detalhados-listados}
saga.rabbitmq.routing-key.gerente.listar-ativos-detalhado.falha=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_LISTAR_ATIVOS_DETALHADO_FALHA:gerente.listagem-ativos-detalhados.falhou}

# Saga Remoção de Gerente
saga.rabbitmq.queue.gerente.listar-ativos.command=${SAGA_RABBITMQ_QUEUE_GERENTE_LISTAR_ATIVOS_COMMAND:gerente.listar-ativos.command}
saga.rabbitmq.routing-key.gerente.listar-ativos.command=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_LISTAR_ATIVOS_COMMAND:gerente.listar-ativos}
saga.rabbitmq.routing-key.gerente.listar-ativos.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_LISTAR_ATIVOS_SUCESSO:gerente.ativos-listados}
saga.rabbitmq.routing-key.gerente.listar-ativos.falha=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_LISTAR_ATIVOS_FALHA:gerente.listagem-ativos.falhou}
saga.rabbitmq.queue.gerente.remover.command=${SAGA_RABBITMQ_QUEUE_GERENTE_REMOVER_COMMAND:gerente.remover.command}
saga.rabbitmq.routing-key.gerente.remover.command=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_REMOVER_COMMAND:gerente.remover}
saga.rabbitmq.routing-key.gerente.remover.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_REMOVER_SUCESSO:gerente.removido}
saga.rabbitmq.routing-key.gerente.remover.falha=${SAGA_RABBITMQ_ROUTING_KEY_GERENTE_REMOVER_FALHA:gerente.remocao.falhou}
