spring.application.name=ms-gerente

# Docker Compose integration
spring.docker.compose.lifecycle-management=start-only
# spring.docker.compose.file=../docker-compose.yml

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gerente?currentSchema=schema_gerente
spring.datasource.username=postgres_user
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=schema_gerente
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true