spring.application.name=ms-gerente
server.port=${SERVER_PORT:8084}

# Docker Compose integration
spring.docker.compose.lifecycle-management=start-only
# spring.docker.compose.file=../docker-compose.yml

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bantads}?currentSchema=schema_gerente
spring.datasource.username=${POSTGRES_USER:postgres_user}
spring.datasource.password=${POSTGRES_PASSWORD:postgres_bantads}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=schema_gerente
