spring.application.name=auth

#Server
server.port=${SERVER_PORT:8081}

#MongoDB
spring.data.mongodb.host=${MONGO_HOST:localhost}
spring.data.mongodb.port=${MONGO_PORT:27017}
spring.data.mongodb.database=${MONGO_DATABASE:bantads_auth}

#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:bantads}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:bantads}

# Saga Messaging
saga.rabbitmq.exchange=${SAGA_RABBITMQ_EXCHANGE:bantads.saga}
saga.rabbitmq.queue.auth.criar-usuario-cliente.command=${SAGA_RABBITMQ_QUEUE_AUTH_CRIAR_USUARIO_CLIENTE_COMMAND:auth.criar-usuario-cliente.command}
saga.rabbitmq.queue.auth.excluir-usuario-cliente.command=${SAGA_RABBITMQ_QUEUE_AUTH_EXCLUIR_USUARIO_CLIENTE_COMMAND:auth.excluir-usuario-cliente.command}
saga.rabbitmq.queue.auth.alterar-usuario-cliente.command=${SAGA_RABBITMQ_QUEUE_AUTH_ALTERAR_USUARIO_CLIENTE_COMMAND:auth.alterar-usuario-cliente.command}
saga.rabbitmq.queue.auth.reverter-alteracao-usuario-cliente.command=${SAGA_RABBITMQ_QUEUE_AUTH_REVERTER_ALTERACAO_USUARIO_CLIENTE_COMMAND:auth.reverter-alteracao-usuario-cliente.command}
saga.rabbitmq.routing-key.auth.criar-usuario-cliente.command=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_CRIAR_USUARIO_CLIENTE_COMMAND:auth.criar-usuario-cliente.command}
saga.rabbitmq.routing-key.auth.criar-usuario-cliente.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_CRIAR_USUARIO_CLIENTE_SUCESSO:auth.usuario-cliente-criado}
saga.rabbitmq.routing-key.auth.criar-usuario-cliente.falha=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_CRIAR_USUARIO_CLIENTE_FALHA:auth.criacao-usuario-cliente.falhou}
saga.rabbitmq.routing-key.auth.excluir-usuario-cliente.command=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_EXCLUIR_USUARIO_CLIENTE_COMMAND:auth.excluir-usuario-cliente.command}
saga.rabbitmq.routing-key.auth.excluir-usuario-cliente.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_EXCLUIR_USUARIO_CLIENTE_SUCESSO:auth.usuario-cliente-excluido}
saga.rabbitmq.routing-key.auth.excluir-usuario-cliente.falha=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_EXCLUIR_USUARIO_CLIENTE_FALHA:auth.exclusao-usuario-cliente.falhou}
saga.rabbitmq.routing-key.auth.alterar-usuario-cliente.command=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_ALTERAR_USUARIO_CLIENTE_COMMAND:auth.alterar-usuario-cliente.command}
saga.rabbitmq.routing-key.auth.alterar-usuario-cliente.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_ALTERAR_USUARIO_CLIENTE_SUCESSO:auth.usuario-cliente-alterado}
saga.rabbitmq.routing-key.auth.alterar-usuario-cliente.falha=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_ALTERAR_USUARIO_CLIENTE_FALHA:auth.alteracao-usuario-cliente.falhou}
saga.rabbitmq.routing-key.auth.reverter-alteracao-usuario-cliente.command=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_REVERTER_ALTERACAO_USUARIO_CLIENTE_COMMAND:auth.reverter-alteracao-usuario-cliente}
saga.rabbitmq.routing-key.auth.reverter-alteracao-usuario-cliente.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_REVERTER_ALTERACAO_USUARIO_CLIENTE_SUCESSO:auth.usuario-cliente-revertido}
saga.rabbitmq.routing-key.auth.reverter-alteracao-usuario-cliente.falha=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_REVERTER_ALTERACAO_USUARIO_CLIENTE_FALHA:auth.reversao-usuario-cliente.falhou}
saga.rabbitmq.queue.auth.criar-usuario-gerente.command=${SAGA_RABBITMQ_QUEUE_AUTH_CRIAR_USUARIO_GERENTE_COMMAND:auth.criar-usuario-gerente.command}
saga.rabbitmq.routing-key.auth.criar-usuario-gerente.command=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_CRIAR_USUARIO_GERENTE_COMMAND:auth.criar-usuario-gerente.command}
saga.rabbitmq.routing-key.auth.criar-usuario-gerente.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_CRIAR_USUARIO_GERENTE_SUCESSO:auth.usuario-gerente-criado}
saga.rabbitmq.routing-key.auth.criar-usuario-gerente.falha=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_CRIAR_USUARIO_GERENTE_FALHA:auth.criacao-usuario-gerente.falhou}
saga.rabbitmq.queue.auth.excluir-usuario-gerente-compensacao.command=${SAGA_RABBITMQ_QUEUE_AUTH_EXCLUIR_USUARIO_GERENTE_COMPENSACAO_COMMAND:auth.excluir-usuario-gerente-compensacao.command}
saga.rabbitmq.routing-key.auth.excluir-usuario-gerente-compensacao.command=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_EXCLUIR_USUARIO_GERENTE_COMPENSACAO_COMMAND:auth.excluir-usuario-gerente-compensacao}
saga.rabbitmq.routing-key.auth.excluir-usuario-gerente-compensacao.sucesso=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_EXCLUIR_USUARIO_GERENTE_COMPENSACAO_SUCESSO:auth.usuario-gerente-excluido-compensacao}
saga.rabbitmq.routing-key.auth.excluir-usuario-gerente-compensacao.falha=${SAGA_RABBITMQ_ROUTING_KEY_AUTH_EXCLUIR_USUARIO_GERENTE_COMPENSACAO_FALHA:auth.exclusao-usuario-gerente-compensacao.falhou}

#JWT
jwt.secret=${JWT_SECRET:d8f2a1b9c7e4503f6a8d1e2b9c7f4a3e5d6b8a1c9e7f2043a5b8d1e6c9f7a2b}
jwt.expiration=${JWT_EXPIRATION:28800000}
