spring.application.name=auth

#Server
server.port=${SERVER_PORT:8081}

#MongoDB
spring.data.mongodb.host=${MONGO_HOST:localhost}
spring.data.mongodb.port=${MONGO_PORT:27017}
spring.data.mongodb.database=${MONGO_DATABASE:bantads_auth}

#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:bantads}
spring.rabbitmq.password=${RABBITMQ_PASS:bantads}

#JWT
jwt.secret=${JWT_SECRET:d8f2a1b9c7e4503f6a8d1e2b9c7f4a3e5d6b8a1c9e7f2043a5b8d1e6c9f7a2b}
jwt.expiration=${JWT_EXPIRATION:28800000}
